name: Changelog Date Check

on:
  push:
    branches: [main]
    paths:
      - 'CHANGELOG.md'
      - 'CHANGELOG_BBCODE.txt'
      - 'CHANGELOG_GFM.txt'
      - 'CHANGELOG_COMMONMARK.txt'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: MPHONlC/changelog-date-check@Version-0.0.1
        with:
          bbcode_file: 'CHANGELOG_BBCODE.txt'
          manifest_file: 'PermMemento.addon'
