name: Dependency Version Check

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: MPHONlC/eso-dependency-check@Version-0.0.2
        with:
          manifest_file: 'PermMemento.addon'
          dependency_name: 'LibAPH'
          dependency_manifest_url: 'https://raw.githubusercontent.com/MPHONlC/LibAPH/main/LibAPH.addon'
          auto_update: true
          git_name: 'MPHONlC'
          git_email: '207844175+MPHONlC@users.noreply.github.com'
