name: Localization Check

on:
  push:
    branches: [main]
    paths:
      - 'lang/*.lua'
  workflow_dispatch:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: MPHONlC/localization-check@Version-0.0.1
        with:
          lang_glob: 'lang/*.lua'
          reference: 'en.lua'
