name: Slash Command Doc Check

on:
  push:
    branches: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: ./.github/actions/eso-slash-command-doc-check
        with:
          doc_files: |
            README_BBCODE.txt
            README.md
            README_COMMONMARK.txt
          ignore_commands: '/pmemsimulateerror'
